# Generated by Django 3.1.6 on 2021-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_chef'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img2', models.ImageField(upload_to='testimonal')),
                ('decription', models.TextField()),
                ('name1', models.CharField(max_length=100)),
            ],
        ),
    ]
