# Generated by Django 3.1.6 on 2021-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_testimonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img3', models.ImageField(upload_to='parties')),
                ('price', models.IntegerField()),
                ('party', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
                ('allocate', models.CharField(max_length=50)),
            ],
        ),
    ]
